#nullable enable
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using OSCommander;
using OSCommander.Models;
using WebApi.Dtos.Internal;
using WebApi.Models.Internal;
using WebApi.Utilities;

namespace WebApi.Services
{

    public class PartitionService
    {

        private readonly Mount _mount;
        private readonly Cron _cron;

        public PartitionService(ILogger logger)
        {
            _mount = new Mount(logger);
            _cron = new Cron(logger);
        }

        public PartitionService(ILogger logger, OSCommander.Dtos.SshCredentials ssh)
        {
            _mount = new Mount(logger, ssh);
            _cron = new Cron(logger, ssh);
        }

        /// <summary>
        /// Enable auto mount partition to /mnt/armnas/{display-name}
        /// </summary>
        public EndpointResult<bool> CheckAutoMount(string uuid, Partition partition)
        {
            try
            {
                var result = new EndpointResult<bool>();
                var kebabDisplayName = partition.DisplayName.ToKebabCase();
                var res = _cron.Check("@reboot", $"sudo mount -t auto /dev/disk/by-uuid/{uuid} /mnt/armnas/{kebabDisplayName}");
                result.Succeed = true;
                result.Result = res;
                return result;
            }
            catch (Exception) // details are logged in OSCommander's ILogger
            {
                return new EndpointResult<bool>()
                {
                    Succeed = false,
                    ErrorMessage = "http.autoMountCheckError",
                    StatusCode = 461
                };
            }
        }

        /// <summary>
        /// Enable auto mount partition to /mnt/armnas/{display-name}
        /// </summary>
        public EndpointResult<string> EnableAutoMount(string uuid, Partition partition)
        {
            try
            {
                var result = new EndpointResult<string>();
                var kebabDisplayName = partition.DisplayName.ToKebabCase();
                _cron.Add("@reboot", $"sudo mount -t auto /dev/disk/by-uuid/{uuid} /mnt/armnas/{kebabDisplayName}");
                result.Succeed = true;
                result.Result = "Partition auto mount enabled.";
                return result;
            }
            catch (Exception) // details are logged in OSCommander's ILogger
            {
                return new EndpointResult<string>()
                {
                    Succeed = false,
                    ErrorMessage = "http.autoMountEnableError",
                    StatusCode = 461
                };
            }
        }

        /// <summary>
        /// Enable auto mount partition to /mnt/armnas/{display-name}
        /// </summary>
        public EndpointResult<string> DisableAutoMount(string uuid, Partition partition)
        {
            try
            {
                var result = new EndpointResult<string>();
                var kebabDisplayName = partition.DisplayName.ToKebabCase();
                _cron.Remove($"sudo mount -t auto /dev/disk/by-uuid/{uuid} /mnt/armnas/{kebabDisplayName}");
                result.Succeed = true;
                result.Result = "Partition auto mount disabled.";
                return result;
            }
            catch (Exception) // details are logged in OSCommander's ILogger
            {
                return new EndpointResult<string>()
                {
                    Succeed = false,
                    ErrorMessage = "http.autoMountDisableError",
                    StatusCode = 461
                };
            }
        }

        /// <summary>
        /// Mount partition to /mnt/armnas/{display-name}
        /// <param name="partition">Partition. Mounting path will be generated by "DisplayName" prop.</param>
        /// <param name="lsblkInfo">If provided, partition will be mounted only, if there are no other
        /// mounted partitions in generated path.</param>
        /// </summary>
        public EndpointResult<string> Mount(string uuid, Partition partition, Lsblk? lsblkInfo)
        {
            try
            {
                var kebabDisplayName = partition.DisplayName.ToKebabCase();
                if (lsblkInfo != null && lsblkInfo.BlockDevices
                    .Where(dev => dev.Children != null)
                    .SelectMany(dev => dev.Children)
                    .Any(part => part.MountPoint == $"/mnt/armnas/{kebabDisplayName}"))
                    return new EndpointResult<string>()
                    {
                        Succeed = false,
                        ErrorMessage = "http.alreadyMounted",
                        StatusCode = 462,
                        Result = $"Partition /mnt/armnas/{kebabDisplayName} is already mounted!"
                    };
                _mount.MountByUuid(uuid, kebabDisplayName);
                return new EndpointResult<string> { Succeed = true, Result = "Partition mounted" };
            }
            catch (Exception) // details are logged in OSCommander's ILogger
            {
                return new EndpointResult<string>()
                {
                    Succeed = false,
                    ErrorMessage = "http.mountError",
                    StatusCode = 461
                };
            }
        }

        /// <summary>
        /// Unmount partition from /mnt/armnas/{display-name}
        /// </summary>
        public EndpointResult<string> Unmount(Partition partition)
        {
            try
            {
                var result = new EndpointResult<string>();
                var kebabDisplayName = partition.DisplayName.ToKebabCase();
                _mount.Unmount(kebabDisplayName);
                result.Succeed = true;
                return result;
            }
            catch (Exception) // details are logged in OSCommander's ILogger
            {
                return new EndpointResult<string>()
                {
                    Succeed = false,
                    ErrorMessage = "http.unmountError",
                    StatusCode = 461
                };
            }
        }

    }

}
