name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  dotnet_angular:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.5
      with:
        default_bump: patch
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.x
        
    - name: Install Angular
      run: |
        npm install @angular/cli -g
       
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish --no-restore -c Release /p:version=${{ steps.tag_version.outputs.new_version }} /p:build=$GITHUB_RUN_ID --output "./publish"
      working-directory: ./backend/WebApi/

    - name: Upload .NET Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: web-api
        path: ./backend/WebApi/publish

    - name: Install Angular dependencies
      run: |
        npm ci
      working-directory: ./frontend/web-app

    - name: Build
      run: |
        ng build --configuration=production --output-hashing=all --output-path=./dist
      working-directory: ./frontend/web-app
      
    - name: Upload Angular Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: web-app
        path: ./frontend/web-app/dist
        
    - name: Create a Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "web-app.zip,web-api.zip"
        body: ${{ steps.tag_version.outputs.changelog }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
