name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_net:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Git Tag Generator
      uses: ChloePlanet/github-tag-action@2.0.0
    
    - name: Change directory
      run: |
        cd backend/WebApi
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Build Number Generator
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}   

    - name: Build
      run: dotnet publish --no-restore -c Release /p:version=$new_tag /p:build=$BUILD_NUMBER --output "./publish"
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: webapi
        path: ./backend/WebApi/publish

  build_angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Angular Full CI
        uses: colbyhill21/angular-full-ci/@v1.0
        with:
          testcommand: run test:ci
          mocha: true
          working-directory: ./frontend/web-app
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: webapp
          path: ./frontend/web-app/dist
