name: Lint Commit Messages
on: [pull_request]

jobs:
  commit_lint:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Lint commit
        id: linter
        uses: wagoid/commitlint-github-action@v2.0.3
        with:
          failOnWarnings: false
