name: Lint Commit Messages
on: [pull_request]

jobs:
  commit_lint:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Lint commit
        id: linter
        uses: wagoid/commitlint-github-action@v3
        with:
          failOnWarnings: false
        #continue-on-error: true
        
      - name: Add lint comment
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{ steps.linter.outputs.results }}
